server:
  port: 3000
spring:
  datasource:
    url: jdbc:h2:file:./db/database.db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  liquibase:
    change-log: file:./db/changelog.xml
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
weather_data_api: https://www.ilmateenistus.ee/ilma_andmed/xml/observations.php